apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 4m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  patches:
    - patch: |-
        apiVersion: autoscaling/v2
        kind: Kustomization
        metadata:
          name: podinfo
        spec:
          minReplicas: 5           
      target:
        name: podinfo
        kind: HorizontalPodAutoscaler
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
