name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      
      # Install Minikube CLI
      - name: Install Minikube CLI
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
          minikube version

      # Set up kubeconfig for Minikube
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config


      # Verify Kubernetes context
      - name: Verify Kubernetes context
        run: |
          kubectl config get-contexts
          kubectl get nodes

      # Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f clusters/minikube-cluster/flux-system/base
